//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantSystem.Model
{
	using RestaurantSystem.ViewModel;
	using System;
    using System.Collections.Generic;
    
    public partial class BillInfo : BaseViewModel
    {
        public int Id { get; set; }

        public Nullable<int> IdBill { get; set; }

        public Nullable<int> IdFood { get; set; }

		private Nullable<int> _Count;
		public Nullable<int> Count { get => _Count; set { _Count = value;OnPropertyChanged(); } }

		private Bill _Bill;
		public virtual Bill Bill { get => _Bill; set { _Bill = value; OnPropertyChanged(); } }

		private Food _Food;
		public virtual Food Food { get => _Food; set { _Food = value; OnPropertyChanged(); } }
    }
}
