//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantSystem.Model
{
	using RestaurantSystem.ViewModel;
	using System;
    using System.Collections.Generic;
    
    public partial class Food : BaseViewModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Food()
        {
            this.BillInfo = new HashSet<BillInfo>();
            this.GoodsForFood = new HashSet<GoodsForFood>();
        }
    
        public int Id { get; set; }

		private string _Name;
        public string Name { get => _Name; set { _Name = value; OnPropertyChanged(); } }

		private Nullable<double> _Price;
		public Nullable<double> Price { get => _Price; set { _Price = value; OnPropertyChanged(); } }

		private Nullable<int> _IdCategoryFood;
		public Nullable<int> IdCategoryFood { get => _IdCategoryFood; set { _IdCategoryFood = value; OnPropertyChanged(); } }

		private Nullable<int> _IdUnit;
		public Nullable<int> IdUnit { get => _IdUnit; set { _IdUnit = value; OnPropertyChanged(); } }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BillInfo> BillInfo { get; set; }

		private CategoryFood _CategoryFood;
		public virtual CategoryFood CategoryFood { get => _CategoryFood; set { _CategoryFood = value; OnPropertyChanged(); } }

		private Unit _Unit;
		public virtual Unit Unit { get => _Unit; set { _Unit = value; OnPropertyChanged(); } }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GoodsForFood> GoodsForFood { get; set; }
    }
}
