//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantSystem.Model
{
	using RestaurantSystem.ViewModel;
	using System;
    using System.Collections.Generic;
    
    public partial class GoodsForFood : BaseViewModel
    {
        public int Id { get; set; }

		private Nullable<int> _IdFood;
		public Nullable<int> IdFood { get => _IdFood; set { _IdFood = value; OnPropertyChanged(); } }

		private Nullable<int> _IdGoods;
		public Nullable<int> IdGoods { get => _IdGoods; set { _IdGoods = value; OnPropertyChanged(); } }

		private Nullable<double> _Count;
		public Nullable<double> Count { get => _Count; set { _Count = value; OnPropertyChanged(); } }

		private Food _Food;
		public virtual Food Food { get => _Food; set { _Food = value; OnPropertyChanged(); } }

		private Goods _Goods;
		public virtual Goods Goods { get => _Goods; set { _Goods = value; OnPropertyChanged(); } }
    }
}
