//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantSystem.Model
{
	using RestaurantSystem.ViewModel;
	using System;
    using System.Collections.Generic;
    
    public partial class Goods : BaseViewModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Goods()
        {
            this.GoodsForFood = new HashSet<GoodsForFood>();
            this.InputInfo = new HashSet<InputInfo>();
            this.OutputInfo = new HashSet<OutputInfo>();
        }
    
        public int Id { get; set; }

		private string _Name;
        public string Name { get => _Name; set { _Name = value; OnPropertyChanged(); } }

		private Nullable<int> _Status;
		public Nullable<int> Status { get => _Status; set { _Status = value; OnPropertyChanged(); } }

		private Nullable<int> _IdUnit;
		public Nullable<int> IdUnit { get => _IdUnit; set { _IdUnit = value; OnPropertyChanged(); } }

		private Unit _Unit;
		public virtual Unit Unit { get => _Unit; set { _Unit = value; OnPropertyChanged(); } }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GoodsForFood> GoodsForFood { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InputInfo> InputInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OutputInfo> OutputInfo { get; set; }
    }
}
