//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantSystem.Model
{
	using RestaurantSystem.ViewModel;
	using System;
    using System.Collections.Generic;
    
    public partial class Input : BaseViewModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Input()
        {
            this.InputInfo = new HashSet<InputInfo>();
        }
    
        public string Id { get; set; }

		private Nullable<System.DateTime> _DateInput;
		public Nullable<System.DateTime> DateInput { get => _DateInput; set { _DateInput = value; OnPropertyChanged(); } }

		private string _MoreInfo;
		public string MoreInfo { get => _MoreInfo; set { _MoreInfo = value; OnPropertyChanged(); } }

		private string _IdStaff;
		public string IdStaff { get => _IdStaff; set { _IdStaff = value; OnPropertyChanged(); } }

		private string _IdSupplier;
		public string IdSupplier { get => _IdSupplier; set { _IdSupplier = value; OnPropertyChanged(); } }

		private Staff _Staff;
		public virtual Staff Staff { get => _Staff; set { _Staff = value; OnPropertyChanged(); } }

		private Supplier _Supplier;
		public virtual Supplier Supplier { get => _Supplier; set { _Supplier = value; OnPropertyChanged(); } }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InputInfo> InputInfo { get; set; }
    }
}
