//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantSystem.Model
{
	using RestaurantSystem.ViewModel;
	using System;
    using System.Collections.Generic;
    
    public partial class InputInfo : BaseViewModel
    {
        public int Id { get; set; }

		private string _IdInput;
		public string IdInput { get => _IdInput; set { _IdInput = value; OnPropertyChanged(); } }

		private Nullable<int> _IdGoods;
		public Nullable<int> IdGoods { get => _IdGoods; set { _IdGoods = value; OnPropertyChanged(); } }

		private Nullable<double> _Count;
		public Nullable<double> Count { get => _Count; set { _Count = value; OnPropertyChanged(); } }

		private Nullable<double> _InputPrice;
		public Nullable<double> InputPrice { get => _InputPrice; set { _InputPrice = value; OnPropertyChanged(); } }

		private Goods _Goods;
		public virtual Goods Goods { get => _Goods; set { _Goods = value; OnPropertyChanged(); } }

		private Input _Input;
		public virtual Input Input { get => _Input; set { _Input = value; OnPropertyChanged(); } }
    }
}
