//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantSystem.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RestaurantSystemEntities : DbContext
    {
        public RestaurantSystemEntities()
            : base("name=RestaurantSystemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bill> Bill { get; set; }
        public virtual DbSet<BillInfo> BillInfo { get; set; }
        public virtual DbSet<CategoryFood> CategoryFood { get; set; }
        public virtual DbSet<Food> Food { get; set; }
        public virtual DbSet<Goods> Goods { get; set; }
        public virtual DbSet<GoodsForFood> GoodsForFood { get; set; }
        public virtual DbSet<Input> Input { get; set; }
        public virtual DbSet<InputInfo> InputInfo { get; set; }
        public virtual DbSet<Output> Output { get; set; }
        public virtual DbSet<OutputInfo> OutputInfo { get; set; }
        public virtual DbSet<Region> Region { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<Staff> Staff { get; set; }
        public virtual DbSet<Supplier> Supplier { get; set; }
        public virtual DbSet<TableFood> TableFood { get; set; }
        public virtual DbSet<Unit> Unit { get; set; }
    }
}
