//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantSystem.Model
{
	using RestaurantSystem.ViewModel;
	using System;
    using System.Collections.Generic;
    
    public partial class Output : BaseViewModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Output()
        {
            this.OutputInfo = new HashSet<OutputInfo>();
        }
    
        public string Id { get; set; }

		private Nullable<System.DateTime> _DateOutput;
		public Nullable<System.DateTime> DateOutput { get => _DateOutput; set { _DateOutput = value; OnPropertyChanged(); } }

		private string _MoreInfo;
		public string MoreInfo { get => _MoreInfo; set { _MoreInfo = value; OnPropertyChanged(); } }

		private string _IdStaff;
		public string IdStaff { get => _IdStaff; set { _IdStaff = value; OnPropertyChanged(); } }

		private Staff _Staff;
		public virtual Staff Staff { get => _Staff; set { _Staff = value; OnPropertyChanged(); } }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OutputInfo> OutputInfo { get; set; }
    }
}
