//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantSystem.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OutputInfo
    {
        public int Id { get; set; }
        public string IdOutput { get; set; }
        public Nullable<int> IdGoods { get; set; }
        public Nullable<double> Count { get; set; }
    
        public virtual Goods Goods { get; set; }
        public virtual Output Output { get; set; }
    }
}
