//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantSystem.Model
{
	using RestaurantSystem.ViewModel;
	using System;
    using System.Collections.Generic;
    
    public partial class Staff : BaseViewModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Staff()
        {
            this.Bill = new HashSet<Bill>();
            this.Input = new HashSet<Input>();
            this.Output = new HashSet<Output>();
        }
    
        public string Id { get; set; }

		private string _UserName;
		public string UserName { get => _Name; set { _Name = value; OnPropertyChanged(); } }

		private string _Password;
		public string Password { get => _Name; set { _Name = value; OnPropertyChanged(); } }

		private string _Name;
		public string Name { get => _Name; set { _Name = value; OnPropertyChanged(); } }

		private Nullable<int> _IdRole;
		public Nullable<int> IdRole { get => _IdRole; set { _IdRole = value; OnPropertyChanged(); } }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bill> Bill { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Input> Input { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Output> Output { get; set; }

		private Role _Role;
		public virtual Role Role { get => _Role; set { _Role = value; OnPropertyChanged(); } }
    }
}
